[client]
# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Default: "auto"
toolbarMode = "viewer"

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

